### ISSUE TITLE
Please use certifi library

### ISSUE THREAD

**Issue by dupuy** [daniperez/vale-python-package#39]
When I use the Vale Python package I am getting the unfortunate error:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
```
Fixing this requires finding the OS or Python install certificate bundle and updating it, which is hard for less technical users. If the vale self installer used the `certifi` package instead, the fix is as simple and platform independent as
```
pip install -U certifi
```

The code chane is small too:
```
>>> import certifi
>>> certifi_context = ssl.create_default_context(cafile=certifi.where())
>>> urlopen("...", context=certifi_context)
```

**Comment by daniperez** [comment]
Hi @dupuy ! Thanks for the advise :+1: 

Can you provide more context as to why that error happens? Unfortunately (or not!) it doesn't happen in my testing environment. I would like to understand why that happens and why an alternative certificate store is needed. I'd like to avoid fixing this for some people but then potentially breaking to other people. 

Please bear with me, from my questions you can see how much I ignore about the subject.

**Comment by daniperez** [comment]
Answering myself:

> If you have installed Python 3.6 on OSX and are getting the "SSL: CERTIFICATE_VERIFY_FAILED" error when trying to connect to an https:// site, it's probably because Python 3.6 on OSX has no certificates at all, ... ([Stackoverflow](https://stackoverflow.com/a/42334357))

Is it something like that?

**Comment by dupuy** [comment]
I'm having this problem using Python 3.10 on macOS Ventura; the more unusual thing is that I was using `pipx` to install vale – but i have the issue even when I use pip to install it:

```
  Using cached pipx-1.4.3-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: argcomplete>=1.9.4 in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from pipx) (3.2.2)
Requirement already satisfied: packaging>=20 in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from pipx) (23.2)
Requirement already satisfied: platformdirs>=2.1 in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from pipx) (4.2.0)
Requirement already satisfied: tomli in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from pipx) (2.0.1)
Requirement already satisfied: userpath!=1.9.0,>=1.6 in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from pipx) (1.9.1)
Requirement already satisfied: click in /Users/alexdupuy/Library/Python/3.10/lib/python/site-packages (from userpath!=1.9.0,>=1.6->pipx) (8.1.7)
Using cached pipx-1.4.3-py3-none-any.whl (65 kB)
Installing collected packages: pipx
Successfully installed pipx-1.4.3
python3 -m pipx install --force pipx
Installing to existing venv 'pipx'
⚠️  Note: pipx was already on your PATH at
    /Users/alexdupuy/Library/Python/3.10/bin/pipx
  installed package pipx 1.4.3, installed using Python 3.10.11
  These apps are now globally available
    - pipx
done! ✨ 🌟 ✨
#yes | python3 -m pip uninstall pipx
/Users/alexdupuy/.local/bin/pipx ensurepath
/Users/alexdupuy/.local/bin is already in PATH.

⚠️  All pipx binary directories have been added to PATH. If you are sure you
want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨
pipx install --force vale
Installing to existing venv 'vale'
  installed package vale 3.0.7.0, installed using Python 3.10.11
  These apps are now globally available
    - vale
done! ✨ 🌟 ✨
* vale not found. Downloading it...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexdupuy/.local/bin/vale", line 10, in <module>
    sys.exit(main())
  File "/Users/alexdupuy/Library/Application Support/pipx/venvs/vale/lib/python3.10/site-packages/vale/main.py", line 158, in main
    vale_bin_path = download_vale_if_missing()
  File "/Users/alexdupuy/Library/Application Support/pipx/venvs/vale/lib/python3.10/site-packages/vale/main.py", line 119, in download_vale_if_missing
    url = urlopen(url_str)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
uninstalled vale! ✨ 🌟 ✨
alexdupuy@Cuchillos reliabot % pip3 -h

Usage:   
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the
                              main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment;
                              exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --keyring-provider <keyring_provider>
                              Enable the credential lookup via the keyring
                              library if user input is allowed. Specify which
                              mechanism to use [disabled, import, subprocess].
                              (default: disabled)
  --proxy <proxy>             Specify a proxy in the form
                              scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming
                              unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.
alexdupuy@Cuchillos reliabot % make uninstall-pipx
rm -rf /Users/alexdupuy/.local/bin
alexdupuy@Cuchillos reliabot % pip3 install vale
Collecting vale
  Using cached vale-3.0.7.0-py3-none-any.whl.metadata (3.0 kB)
Using cached vale-3.0.7.0-py3-none-any.whl (5.7 kB)
Installing collected packages: vale
Successfully installed vale-3.0.7.0
alexdupuy@Cuchillos reliabot % vale sync
* vale not found. Downloading it...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/vale", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vale/main.py", line 158, in main
    vale_bin_path = download_vale_if_missing()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/vale/main.py", line 119, in download_vale_if_missing
    url = urlopen(url_str)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>:
```

**Comment by dupuy** [comment]
Sorry I didn't mean to close the issue, that's what happens when I am commenting right before I go to sleep...

**Comment by daniperez** [comment]
Hi @dupuy ! Finally I can come back to you. Let me know what do you think. Please, bear with me, this is not a subject I'm familiar with.

If I implement what you mention in your first comment, I will be circumventing your OS ability to update the certificates and turn vale into some kind of attack vector (or so I read googling the issue). In this case, my guess is that the attack surface is quite limited, but I'm not a security expert and I guess a lot of security issues originate in otherwise small attack vectors.

I could update the documentation to let users know about this problem and how to fix it.

Out of curiosity: did you try this with your brew's python? (from you last comment)

> If you wish to install a non-brew-packaged Python package,
> create a virtual environment using python3 -m venv path/to/venv.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip.

:green_apple:  **I would like to know what other Mac users are experiencing, because I don't own a Mac and it seems some users can still use this (but that I don't know!).**
